function display_graph(nodes,edges)
%function display_graph(nodes,edges)
% 
% Draw a web with edge and node labels on the current axis
%
% INPUTS
%
% nodes is an nv x d matrix with the coordinates of nodes
%     nodes(i,:) is the location of node i
%     nv is the number of nodes
%     d is the number of spatial dimensions (2 or 3)
%
% edges is an ne x 2 matrix with the indices of connected nodes
%     edges(i,:) contains the indices of the two nodes connected by string i
%     ne is the number of edges

[nv,d] = size(nodes);
ne = size(edges,1);

edge_color = 0.7*[1,1,1];
edge_label_color = 'b';
node_label_color = 'r';

if d == 2
    %----%
    % 2D %
    %----%

    % Plot edges
    plot(...
        [nodes(edges(:,1),1)' ; nodes(edges(:,2),1)'],...
        [nodes(edges(:,1),2)' ; nodes(edges(:,2),2)'],...
        'color',edge_color ...
    );
    % Print edge labels
    for i=1:ne
        loc = mean(nodes(edges(i,:),:),1);
        text(...
            loc(1),loc(2),...
            num2str(i),...
            'verticalalign','middle','horizontalalign','center',...
            'color',edge_label_color...
        );
    end
    % Print node labels
    for i=1:nv
        text(...
            nodes(i,1),nodes(i,2),...
            num2str(i),...
            'verticalalign','middle','horizontalalign','center',...
            'color',node_label_color...
        );
    end
    return;
elseif d~=3
    error('Number of spatial dimensions must be 2 or 3')
end

%----%
% 3D %
%----%

% Plot edges
plot3(...
    [nodes(edges(:,1),1)' ; nodes(edges(:,2),1)'],...
    [nodes(edges(:,1),2)' ; nodes(edges(:,2),2)'],...
    [nodes(edges(:,1),3)' ; nodes(edges(:,2),3)'],...
    'color',edge_color ...
);

% Print edge labels
for i=1:ne
    loc = mean(nodes(edges(i,:),:),1);
    text(...
        loc(1),loc(2),loc(3),...
        num2str(i),...
        'verticalalign','middle','horizontalalign','center',...
        'color',edge_label_color...
    );
end

% Print node labels
for i=1:nv
    text(...
        nodes(i,1),nodes(i,2),nodes(i,3),...
        num2str(i),...
        'verticalalign','middle','horizontalalign','center',...
        'color',node_label_color...
    );
end

